version: '3.9'

services:
  web:
    depends_on:
      - redis
    build: .
    volumes:
      - ./:/var/www/app
      - /var/www/app/node_modules
    ports:
      - ${DOCKER_SERVER_PORT}:${SERVER_PORT}
    env_file:
      - .env
    restart: always
    command: ["nodemon", "server.js"]
  
  redis:
    image: redis:latest
    restart: always
    ports:
      - ${DOCKER_REDIS_PORT}:${REDIS_PORT}
    volumes:
      - redis-data:/root/redis
    env_file:
      - .env

volumes:
  redis-data: {}